title: PrometheusEval
description: Evaluate your LLM's response with Prometheus 💯
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/prometheus-eval/prometheus-eval

enable_copy_code_button: true

